
name: Build plugin

on:
  workflow_dispatch:

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Cloning DWC repository
      uses: actions/checkout@v4
      with:
        repository: Duet3D/DuetWebControl
        path: DuetWebControl
    - name: Setup node
      uses: actions/setup-node@v4
    - run: npm install
      working-directory: DuetWebControl
    - name: Build plugin
      run: npm run build-plugin $GITHUB_WORKSPACE/src
      working-directory: DuetWebControl
    - name: Store the plugin package
      uses: actions/upload-artifact@v3
      with:
        path: $GITHUB_WORKSPACE/DuetWebControl/dist/ExecOnMcode-*.zip
